syntax = "proto3";

package user;

option go_package = "github.com/terminator791/Simple-gRPC-go/pkg/user";

// User service definition
service UserService {
  // Get user by ID
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  // Create a new user
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
  // Login user and get JWT token
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
}

// Request message for GetUser
message GetUserRequest {
  int64 user_id = 1;
}

// Response message for GetUser
message GetUserResponse {
  User user = 1;
}

// Request message for CreateUser
message CreateUserRequest {
  string email = 1;
  string name = 2;
  string password = 3;
}

// Response message for CreateUser
message CreateUserResponse {
  User user = 1;
}

// Request message for LoginUser
message LoginUserRequest {
  string email = 1;
  string password = 2;
}

// Response message for LoginUser
message LoginUserResponse {
  User user = 1;
  string token = 2;
}

// User model
message User {
  int64 id = 1;
  string email = 2;
  string name = 3;
  string role = 4;
  string created_at = 5;
}